## Single-layer Networks

In [21]:
import numpy as np

# reference_ud_uw
v0_single_I_ud_uw = np.load('rocauc_ud_uw_part1.npy')
v0_single_II_ud_uw =  np.load('rocauc_ud_uw_part2.npy')
v0_single_III_ud_uw = np.load('rocauc_ud_uw_part3.npy')

# v1
v1_single_I = np.load('rocauc_v1_ud_w_part1.npy')
v1_single_II =  np.load('rocauc_v1_ud_w_part2.npy')
v1_single_III = np.load('rocauc_v1_ud_w_part3.npy')

# v2
v2_single_I = np.load('rocauc_v2_ud_w_part1_original.npy')
v2_single_II = np.load('rocauc_v2_ud_w_part2_original.npy')
v2_single_III = np.load('rocauc_v2_ud_w_part3_original.npy')

# v2*
v2ast_single_I = np.load('rocauc_v2_ud_w_part1.npy')
v2ast_single_II = np.load('rocauc_v2_ud_w_part2.npy')
v2ast_single_III = np.load('rocauc_v2_ud_w_part3.npy')

In [22]:
v0_single_ud_uw = np.concatenate(
    (v0_single_I_ud_uw, v0_single_II_ud_uw, v0_single_III_ud_uw)
)
print(np.mean(v0_single_ud_uw))

0.5114217094728364


In [23]:
v1_single = np.concatenate((v1_single_I, v1_single_II, v1_single_III))
print(np.mean(v1_single))

0.6518443010022265


In [24]:
v2_single = np.concatenate((v2_single_I, v2_single_II, v2_single_III))
print(np.mean(v2_single))

0.5727075209551201


In [25]:
v2ast_single = np.concatenate((v2ast_single_I, v2ast_single_II, v2ast_single_III))
print(np.mean(v2ast_single))

0.7029216512439069


In [26]:
from statsmodels.sandbox.stats.multicomp import multipletests
from scipy.stats import wilcoxon

In [27]:
print(wilcoxon(v0_single_ud_uw, v1_single, alternative = 'less'))
print(wilcoxon(v0_single_ud_uw, v2_single, alternative = 'less'))
print(wilcoxon(v0_single_ud_uw, v2ast_single, alternative = 'less'))

WilcoxonResult(statistic=276.0, pvalue=2.552791648480553e-17)
WilcoxonResult(statistic=21.0, pvalue=3.6022455930049396e-20)
WilcoxonResult(statistic=0.0, pvalue=2.048086895051651e-20)


In [28]:
multipletests(np.array([2.552791648480553e-17, 3.6022455930049396e-20, 2.048086895051651e-20]), method = 'bonferroni')

(array([ True,  True,  True]),
 array([7.65837495e-17, 1.08067368e-19, 6.14426069e-20]),
 0.016952427508441503,
 0.016666666666666666)

In [29]:
print(wilcoxon(v1_single, v2_single))
print(wilcoxon(v1_single, v2ast_single))
print(wilcoxon(v2_single, v2ast_single))

WilcoxonResult(statistic=791.0, pvalue=5.613640416988119e-12)
WilcoxonResult(statistic=339.0, pvalue=2.377223957972653e-16)
WilcoxonResult(statistic=16.0, pvalue=6.300299589085754e-20)


In [30]:
multipletests(np.array([5.613640416988119e-12, 2.377223957972653e-16, 6.300299589085754e-20]), method = 'bonferroni')

(array([ True,  True,  True]),
 array([1.68409213e-11, 7.13167187e-16, 1.89008988e-19]),
 0.016952427508441503,
 0.016666666666666666)

## Multi-layer Networks

In [31]:
# v0
v0_multi_I = np.load("rocauc_v0_ud_w_part1_multilayer.npy")
v0_multi_II = np.load("rocauc_v0_ud_w_part2_multilayer.npy")
v0_multi_III = np.load("rocauc_v0_ud_w_part3_multilayer.npy")

# v1
v1_multi_I = np.load('rocauc_v1_ud_w_part1_multilayer.npy')
v1_multi_II =  np.load('rocauc_v1_ud_w_part2_multilayer.npy')
v1_multi_III = np.load('rocauc_v1_ud_w_part3_multilayer.npy')

# # v2
v2_multi_I = np.load('rocauc_v2_ud_w_part1_multilayer_original.npy')
v2_multi_II = np.load('rocauc_v2_ud_w_part2_multilayer_original.npy')
v2_multi_III = np.load('rocauc_v2_ud_w_part3_multilayer_original.npy')


In [32]:
v0_multi = np.concatenate((v0_multi_I, v0_multi_II, v0_multi_III))
print(np.mean(v0_multi))

0.6807700158157218


In [33]:
wilcoxon(v0_single_ud_uw, v0_multi, alternative = 'less')


WilcoxonResult(statistic=286.0, pvalue=3.265939066825806e-17)

In [42]:
#dummy test
#wilcoxon([5,5,5,5,5,5,5,1,1,1,1,1], [65,65,65,65,65,25,25,11,11,11,11,11], alternative = 'less')


In [35]:
v1_multi = np.concatenate((v1_multi_I, v1_multi_II, v1_multi_III))
print(np.mean(v1_multi))

0.7166820797768718


In [43]:
wilcoxon(v1_single, v1_multi, alternative = 'less')


WilcoxonResult(statistic=7.0, pvalue=2.4732463753979982e-20)

In [37]:
v2_multi = np.concatenate((v2_multi_I, v2_multi_II, v2_multi_III))
print(np.mean(v2_multi))

0.7480628037743963


In [38]:
wilcoxon(v2_single, v2_multi, alternative = 'less')


WilcoxonResult(statistic=44.0, pvalue=6.657661280184566e-20)

In [39]:
v2ast_multi = []
for j in range(25):
    tmp = np.load('REVISED_rocauc_v2_ud_w_part1_multilayer_iteration_'+str(j)+'.npy')
    v2ast_multi.append(tmp[0])
for j in range(25,50):
    tmp = np.load('REVISED_rocauc_v2_ud_w_part2_multilayer_iteration_'+str(j)+'.npy')
    v2ast_multi.append(tmp[0])
for j in range(50,112):
    tmp = np.load('REVISED_rocauc_v2_ud_w_part3_multilayer_iteration_'+str(j)+'.npy')
    v2ast_multi.append(tmp[0])
print(np.mean(v2ast_multi))
print(len(v2ast_multi))

0.7562992912710721
112


In [40]:
wilcoxon(v2ast_single, v2ast_multi, alternative = 'less')


WilcoxonResult(statistic=46.0, pvalue=7.02144884649228e-20)

In [44]:
multipletests(np.array([3.265939066825806e-17, 2.4732463753979982e-20, 6.657661280184566e-20,
7.02144884649228e-20]), method = 'bonferroni')

(array([ True,  True,  True,  True]),
 array([1.30637563e-16, 9.89298550e-20, 2.66306451e-19, 2.80857954e-19]),
 0.012741455098566168,
 0.0125)

In [45]:
wilcoxon(v2_multi, v2ast_multi, alternative = 'less')


WilcoxonResult(statistic=2895.0, pvalue=0.21741837965301108)

In [41]:
from scipy.stats import wilcoxon
print(wilcoxon(v2ast_single, v0_multi, alternative = 'less'))
print(wilcoxon(v2ast_single, v1_multi, alternative = 'less'))
print(wilcoxon(v2ast_single, v2_multi, alternative = 'less'))
print(wilcoxon(v2ast_single, v2ast_multi, alternative = 'less'))

WilcoxonResult(statistic=4044.0, pvalue=0.9946868513564844)
WilcoxonResult(statistic=2336.0, pvalue=0.008113024803320837)
WilcoxonResult(statistic=1176.0, pvalue=3.930296006873285e-09)
WilcoxonResult(statistic=598.0, pvalue=4.6872389052685854e-14)


In [42]:
multipletests(np.array([0.9946868513564844, 0.008113024803320837, 3.930296006873285e-09, 4.6872389052685854e-14]), method = 'bonferroni')

(array([False,  True,  True,  True]),
 array([1.00000000e+00, 3.24520992e-02, 1.57211840e-08, 1.87489556e-13]),
 0.012741455098566168,
 0.0125)